# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ipad' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ipad:

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FontAwesome.swift'
  pod 'ChromaColorPicker'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Bolts'
  pod 'GoogleSignIn'
  pod 'ScalingCarousel'
  pod 'GoogleAPIClientForREST/Drive', '~> 1.2.1'

end
